server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #register-with-eureka: false 和 fetch-registry: false 表明自己属于服务中心主体
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
